/* NTC chart engine — Phase 3/4/5 compatible. */
(function(global){
"use strict";
function cssVar(name,fallback){try{const v=getComputedStyle(document.documentElement).getPropertyValue(name).trim();return v||fallback}catch(e){return fallback}}
function palette(){return{bg:cssVar("--ntc-bg","#131722"),panel:cssVar("--ntc-panel","#1E222D"),border:cssVar("--ntc-border","#2A2E39"),text:cssVar("--ntc-text","#D1D4DC"),up:cssVar("--ntc-up","#26A69A"),down:cssVar("--ntc-down","#EF5350"),accent:cssVar("--ntc-accent","#2962FF")}}
function ha(candles){let out=[],p=null;for(const c of candles){const close=(c.open+c.high+c.low+c.close)/4,open=p?(p.open+p.close)/2:(c.open+c.close)/2;const x={time:c.time,open,high:Math.max(c.high,open,close),low:Math.min(c.low,open,close),close,volume:c.volume};out.push(x);p=x}return out}
class NTCEngine{
 constructor({chartEl,volEl,onCrosshair}){this.chartEl=chartEl;this.volEl=volEl;this.onCrosshair=onCrosshair||(()=>{});this.chart=null;this.volChart=null;this.mainSeries=null;this.volSeries=null;this.chartType="candles";this._lastCandles=[];this.panes={};this.indicatorSeries=[];this._syncing=false;this._pal=palette();this._init()}
 _common(){const p=this._pal||palette();return{layout:{background:{color:p.bg},textColor:p.text},grid:{vertLines:{color:p.panel},horzLines:{color:p.panel}},rightPriceScale:{borderColor:p.border},timeScale:{borderColor:p.border,timeVisible:false},crosshair:{mode:LightweightCharts.CrosshairMode.Normal},autoSize:false}}
 _init(){const c=this._common();this.chart=LightweightCharts.createChart(this.chartEl,{...c,width:this.chartEl.clientWidth,height:this.chartEl.clientHeight});this.volChart=LightweightCharts.createChart(this.volEl,{...c,width:this.volEl.clientWidth,height:this.volEl.clientHeight,timeScale:{borderColor:this._pal.border,visible:true}});this.volSeries=this.volChart.addHistogramSeries({priceFormat:{type:"volume"},priceScaleId:""});this.volChart.priceScale("").applyOptions({scaleMargins:{top:.15,bottom:0}});this._setMainSeries("candles");this._wire();this._resize();this._onTheme=()=>this.applyTheme();global.addEventListener("ntc-theme-changed",this._onTheme)}
 _wire(){this.chart.subscribeCrosshairMove(p=>{if(this._syncing)return;this._syncing=true;if(p&&p.time)this.volChart.setCrosshairPosition(0,p.time,this.volSeries);else this.volChart.clearCrosshairPosition();this._syncing=false;const price=p&&p.seriesData?p.seriesData.get(this.mainSeries):null;this.onCrosshair(price||null,p)});this.volChart.subscribeCrosshairMove(p=>{if(this._syncing)return;this._syncing=true;if(p&&p.time)this.chart.setCrosshairPosition(0,p.time,this.mainSeries);else this.chart.clearCrosshairPosition();this._syncing=false});const sync=(a,b)=>(r)=>{if(r&&!this._syncing){this._syncing=true;b.timeScale().setVisibleLogicalRange(r);this._syncing=false}};this.chart.timeScale().subscribeVisibleLogicalRangeChange(sync(this.chart,this.volChart));this.volChart.timeScale().subscribeVisibleLogicalRangeChange(sync(this.volChart,this.chart))}
 _resize(){this._ro=new ResizeObserver(()=>{this.chart.applyOptions({width:this.chartEl.clientWidth,height:this.chartEl.clientHeight});this.volChart.applyOptions({width:this.volEl.clientWidth,height:this.volEl.clientHeight});Object.values(this.panes).forEach(p=>{const ce=p.chartEl||p.el;p.chart.applyOptions({width:ce.clientWidth,height:ce.clientHeight})})});this._ro.observe(this.chartEl);this._ro.observe(this.volEl)}
 _setMainSeries(type){if(this.mainSeries)this.chart.removeSeries(this.mainSeries);const p=this._pal||palette(),UP=p.up,DOWN=p.down,ACC=p.accent;let s;switch(type){case"bars":s=this.chart.addBarSeries({upColor:UP,downColor:DOWN});break;case"hollow":s=this.chart.addCandlestickSeries({upColor:"rgba(0,0,0,0)",downColor:DOWN,borderUpColor:UP,borderDownColor:DOWN,wickUpColor:UP,wickDownColor:DOWN});break;case"line":s=this.chart.addLineSeries({color:ACC,lineWidth:2});break;case"area":s=this.chart.addAreaSeries({lineColor:ACC,topColor:ACC+"59",bottomColor:ACC+"05"});break;case"baseline":s=this.chart.addBaselineSeries({topLineColor:UP,topFillColor1:"rgba(38,166,154,.28)",topFillColor2:"rgba(38,166,154,.02)",bottomLineColor:DOWN,bottomFillColor1:"rgba(239,83,80,.02)",bottomFillColor2:"rgba(239,83,80,.28)"});break;default:s=this.chart.addCandlestickSeries({upColor:UP,downColor:DOWN,borderVisible:false,wickUpColor:UP,wickDownColor:DOWN})}this.mainSeries=s;this.chartType=type}
 applyTheme(){this._pal=palette();const c=this._common();this.chart.applyOptions(c);this.volChart.applyOptions({...c,timeScale:{...c.timeScale,visible:true}});Object.values(this.panes).forEach(p=>p.chart.applyOptions({...c,timeScale:{...c.timeScale,visible:true}}));this._setMainSeries(this.chartType);this.render(this._lastCandles);if(this.activeIndicatorsCache)this.renderIndicators(this.activeIndicatorsCache,this._lastCandles)}
 _source(){const c=this._lastCandles||[];switch(this.chartType){case"heikinashi":return ha(c);case"renko":return global.NTC_TRANSFORMS.renko(c,1);case"linebreak":return global.NTC_TRANSFORMS.linebreak(c,3);case"kagi":return global.NTC_TRANSFORMS.kagi(c,4);case"pnf":return global.NTC_TRANSFORMS.pnf(c,1,3);case"range":return global.NTC_TRANSFORMS.range(c,1);default:return c}}
 setChartType(type){if(type===this.chartType)return;this._setMainSeries(type);this.render(this._lastCandles)}
 render(candles){this._lastCandles=candles||[];const src=this._source();if(!src.length){this.mainSeries.setData([]);this.volSeries.setData([]);return}let d;if(["line","area","baseline"].includes(this.chartType)){d=src.map(x=>({time:x.time,value:x.close}));if(this.chartType==="baseline"){const avg=src.reduce((s,x)=>s+x.close,0)/src.length;this.mainSeries.applyOptions({baseValue:{type:"price",price:avg}})}}else d=src.map(x=>({time:x.time,open:x.open,high:x.high,low:x.low,close:x.close}));this.mainSeries.setData(d);this.volSeries.setData(src.map(x=>({time:x.time,value:x.volume||0,color:x.close>=x.open?"rgba(38,166,154,.5)":"rgba(239,83,80,.5)"})));this.chart.timeScale().fitContent();this.volChart.timeScale().fitContent()}
 _pane(id,label,height=180){if(this.panes[id])return this.panes[id];const el=document.createElement("div");el.className="ntc-indicator-pane";el.dataset.pane=id;el.innerHTML='<div class="ntc-indicator-pane-head">'+label+'</div><div class="ntc-indicator-pane-chart"></div>';this.volEl.parentElement.appendChild(el);const chartEl=el.querySelector(".ntc-indicator-pane-chart"),c=this._common();const ch=LightweightCharts.createChart(chartEl,{...c,width:chartEl.clientWidth,height:height,timeScale:{borderColor:"#2A2E39",visible:true}});el.style.height=(height+24)+"px";const pane={el,chart:ch,chartEl};this.panes[id]=pane;ch.timeScale().subscribeVisibleLogicalRangeChange(r=>{if(r&&!this._syncing){this._syncing=true;this.chart.timeScale().setVisibleLogicalRange(r);this._syncing=false}});this.chart.timeScale().subscribeVisibleLogicalRangeChange(r=>{if(r&&!this._syncing){this._syncing=true;ch.timeScale().setVisibleLogicalRange(r);this._syncing=false}});return pane}
 clearIndicators(){this.indicatorSeries.forEach(x=>{try{x.chart.removeSeries(x.series)}catch(e){}});this.indicatorSeries=[];Object.keys(this.panes).forEach(id=>this.panes[id].el.remove());this.panes={}}
 renderIndicators(active,candles){this.activeIndicatorsCache=active;this.clearIndicators();if(!candles||!candles.length)return;const defs=global.NTC_INDICATORS;active.forEach((item,idx)=>{const def=defs.registry[item.id];if(!def)return;let res;try{res=defs.calculate(item.id,candles,item.settings||{})}catch(e){console.warn("[ntc-indicator]",item.id,e);return}if(!res)return;let target=this.chart,paneId="main";if(!res.overlay){paneId="ind_"+idx;const pane=this._pane(paneId,def.name);target=pane.chart}const seriesColor=["#2962FF","#FF9800","#AB47BC","#26A69A","#EF5350","#42A5F5","#FFCA28","#EC407A"];(res.lines||[]).forEach((line,j)=>{const s=target.addLineSeries({color:seriesColor[(idx+j)%seriesColor.length],lineWidth:1,priceLineVisible:false,lastValueVisible:false});s.setData(defs.mapSeries(candles,line[1]));this.indicatorSeries.push({chart:target,series:s,id:item.id});if(paneId!=="main")s.applyOptions({lastValueVisible:true})});if(res.hist){const s=target.addHistogramSeries({priceFormat:{type:"price",precision:2,minMove:.01},base:0,priceScaleId:""});s.setData(defs.mapSeries(candles,res.hist[1]).map(x=>({...x,color:x.value>=0?"rgba(38,166,154,.55)":"rgba(239,83,80,.55)"})));target.priceScale("").applyOptions({scaleMargins:{top:.1,bottom:.1}});this.indicatorSeries.push({chart:target,series:s,id:item.id})}if(res.points){res.points.forEach((pt,j)=>{const s=target.addLineSeries({color:seriesColor[(idx+j)%seriesColor.length],lineWidth:1,priceLineVisible:false,lastValueVisible:false});s.setData(defs.mapSeries(candles,pt[1]));this.indicatorSeries.push({chart:target,series:s,id:item.id})})}if(res.bounds&&paneId!=="main"){res.bounds.forEach(v=>{const s=target.addLineSeries({color:"#5B5F6B",lineWidth:1,lineStyle:LightweightCharts.LineStyle.Dashed,priceLineVisible:false,lastValueVisible:false});s.setData(candles.map(x=>({time:x.time,value:v})));this.indicatorSeries.push({chart:target,series:s,id:item.id})})}if(res.labels&&paneId==="main"){const markers=res.labels.map((x,i)=>x?{time:candles[i].time,position:"aboveBar",color:seriesColor[idx%seriesColor.length],shape:"circle",text:x}:null).filter(Boolean);try{this.mainSeries.setMarkers(markers)}catch(e){}}});Object.values(this.panes).forEach(p=>p.chart.timeScale().fitContent());this.chart.timeScale().fitContent()}
 autoscale(){this.chart.timeScale().fitContent();this.volChart.timeScale().fitContent();Object.values(this.panes).forEach(p=>p.chart.timeScale().fitContent())}
 setScaleMode(mode){const ps=this.chart.priceScale("right");if(mode==="invert")ps.applyOptions({invertScale:true});else ps.applyOptions({invertScale:false,mode:mode==="log"?1:mode==="percent"?2:0})}
 lastPoint(){return this._lastCandles.length?this._lastCandles[this._lastCandles.length-1]:null}
 destroy(){try{global.removeEventListener("ntc-theme-changed",this._onTheme)}catch(e){}try{this._ro&&this._ro.disconnect()}catch(e){}}
}
global.NTCEngine=NTCEngine;
})(window);
