/* NTC Phase 9 — historical replay + backtest. Client-side, no look-ahead. */
(function(global){
  "use strict";
  const KEY="ntc_replay_v1";
  const esc=s=>String(s==null?"":s).replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[m]));
  const money=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  function ema(v,p){const o=Array(v.length).fill(null),k=2/(p+1);let prev=null;for(let i=0;i<v.length;i++){if(i===p-1)prev=v.slice(0,p).reduce((a,b)=>a+b,0)/p;else if(i>=p)prev=v[i]*k+prev*(1-k);if(i>=p-1)o[i]=prev}return o}
  function stats(trades,equity,start){const wins=trades.filter(t=>t.pnl>0),losses=trades.filter(t=>t.pnl<0),grossWin=wins.reduce((a,t)=>a+t.pnl,0),grossLoss=Math.abs(losses.reduce((a,t)=>a+t.pnl,0));let peak=start,maxDD=0;equity.forEach(x=>{peak=Math.max(peak,x);maxDD=Math.max(maxDD,peak-x)});return {trades:trades.length,wins:wins.length,losses:losses.length,winRate:trades.length?wins.length/trades.length*100:0,net:(equity.at(-1)||start)-start,profitFactor:grossLoss?grossWin/grossLoss:(grossWin?Infinity:0),maxDrawdown:maxDD,avgTrade:trades.length?trades.reduce((a,t)=>a+t.pnl,0)/trades.length:0}}
  class Replay{
    constructor({button,modal,body,getActive}){this.button=button;this.modal=modal;this.body=body;this.getActive=getActive;this.item=null;this.running=false;this.timer=null;this.index=0;this.speed=1;this.cash=1000000;this.qty=0;this.avg=0;this.trades=[];this.journal=[];this.equity=[];this._load();button&&button.addEventListener("click",()=>this.open());modal&&modal.addEventListener("click",e=>{if(e.target===modal)this.close()})}
    _load(){try{const s=JSON.parse(localStorage.getItem(KEY)||"null");if(s&&typeof s==="object"){this.speed=Number(s.speed)||1}}catch(e){}}
    _save(){try{localStorage.setItem(KEY,JSON.stringify({speed:this.speed}))}catch(e){}}
    open(){this.stop();this.item=this.getActive();if(!this.item||!this.item.candles.length)return alert("Load a symbol with historical candles first.");this.index=Math.max(0,Math.min(this.item.candles.length-1,Math.floor(this.item.candles.length*.35)));this.resetAccount();this.modal.classList.add("show");this.render();this.apply()}
    close(){this.stop();this.modal.classList.remove("show");if(this.item)this.item.engine.render(this.item.candles),this.item.engine.renderIndicators(this.item.indicators||[],this.item.candles)}
    stop(){this.running=false;if(this.timer){clearTimeout(this.timer);this.timer=null}}
    resetAccount(){this.cash=1000000;this.qty=0;this.avg=0;this.trades=[];this.journal=[];this.equity=[]}
    apply(){if(!this.item)return;const visible=this.item.candles.slice(0,this.index+1);this.item.engine.render(visible);this.item.engine.renderIndicators(this.item.indicators||[],visible);const c=visible.at(-1);if(c){this.equity.push(this.cash+this.qty*c.close)}this.render()}
    step(delta){this.stop();this.index=Math.max(0,Math.min(this.item.candles.length-1,this.index+delta));this.apply()}
    play(){if(this.running)return;this.running=true;const tick=()=>{if(!this.running)return;if(this.index>=this.item.candles.length-1){this.stop();this.render();return}this.index++;this.apply();this.timer=setTimeout(tick,Math.max(80,800/this.speed))};tick()}
    order(side){const c=this.item&&this.item.candles[this.index];if(!c)return;const q=Math.floor(Number(document.getElementById("ntcReplayQty")?.value)||0);if(q<1)return alert("Enter a valid quantity.");const px=c.close;if(side==="buy"){const cost=px*q;if(cost>this.cash)return alert("Not enough replay cash.");this.avg=(this.avg*this.qty+cost)/(this.qty+q);this.qty+=q;this.cash-=cost;this.journal.unshift({date:c.time,action:"BUY",qty:q,price:px,pnl:0})}else{if(q>this.qty)return alert("Not enough replay shares.");const pnl=(px-this.avg)*q;this.cash+=px*q;this.qty-=q;if(!this.qty)this.avg=0;this.trades.unshift({date:c.time,side:"SELL",qty:q,price:px,pnl});this.journal.unshift({date:c.time,action:"SELL",qty:q,price:px,pnl})}this.apply()}
    runBacktest(){const c=this.item.candles,fast=Math.max(2,Number(document.getElementById("ntcBtFast")?.value)||10),slow=Math.max(fast+1,Number(document.getElementById("ntcBtSlow")?.value)||20),start=Math.max(slow,c.length>30?Math.floor(c.length*.1):slow),initial=Math.max(1000,Number(document.getElementById("ntcBtCash")?.value)||1000000),fees=Math.max(0,Number(document.getElementById("ntcBtFees")?.value)||0)/10000;let cash=initial,qty=0,avg=0;const f=ema(c.map(x=>x.close),fast),s=ema(c.map(x=>x.close),slow),tr=[],eq=[];for(let i=start;i<c.length;i++){const prevBull=f[i-1]!=null&&s[i-1]!=null&&f[i-1]<=s[i-1],bull=f[i]!=null&&s[i]!=null&&f[i]>s[i];const prevBear=f[i-1]!=null&&s[i-1]!=null&&f[i-1]>=s[i-1],bear=f[i]!=null&&s[i]!=null&&f[i]<s[i];if(prevBull&&bull&&qty===0){const px=c[i].open,cost=px*(Math.floor(cash/px));if(cost>0){const q=Math.floor(cash/(px*(1+fees)));qty=q;avg=px;cash-=px*q*(1+fees)}}else if(prevBear&&bear&&qty>0){const px=c[i].open;const pnl=(px-avg)*qty-px*qty*fees;cash+=px*qty*(1-fees);tr.push({date:c[i].time,side:"SELL",qty,price:px,pnl});qty=0;avg=0}eq.push(cash+qty*c[i].close)}if(qty){const last=c.at(-1),pnl=(last.close-avg)*qty-last.close*qty*fees;cash+=last.close*qty*(1-fees);tr.push({date:last.time,side:"SELL",qty,price:last.close,pnl});eq.push(cash)}const st=stats(tr,eq,initial);this.body.querySelector("#ntcBacktestResult").innerHTML=this.statsHtml(st,tr,initial,c.at(-1)?.time);}
    statsHtml(st,tr,initial,last){return `<div class="ntc-replay-stats">${[["Net P&L",money(st.net)], ["Trades",st.trades],["Win rate",st.winRate.toFixed(1)+"%"],["Profit factor",st.profitFactor===Infinity?"∞":st.profitFactor.toFixed(2)],["Max drawdown",money(st.maxDrawdown)],["Avg trade",money(st.avgTrade)]].map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join("")}</div><div class="ntc-replay-table-wrap"><table><thead><tr><th>Date</th><th>Side</th><th>Qty</th><th>Price</th><th>P&L</th></tr></thead><tbody>${tr.slice(0,100).map(t=>`<tr><td>${esc(t.date)}</td><td>${t.side}</td><td>${t.qty}</td><td>${money(t.price)}</td><td>${money(t.pnl)}</td></tr>`).join("")||`<tr><td colspan="5">No trades generated.</td></tr>`}</tbody></table></div><div class="ntc-replay-note">Strategy: EMA crossover; entries/exits execute at the next candle open. Initial cash ${money(initial)}. Last bar ${esc(last||"")}.</div>`}
    render(){if(!this.body)return;const c=this.item.candles[this.index],total=this.item.candles.length,acct=this.cash+this.qty*(c?.close||0);this.body.innerHTML=`<div class="ntc-replay-head"><b>${esc(this.item.symbol)}</b><span>Replay ${this.index+1}/${total}</span><span class="spacer"></span><button class="ntc-btn" id="ntcReplayClose">Close</button></div><div class="ntc-replay-controls"><button class="ntc-btn" id="ntcReplayStart">${this.running?"Pause":"Play"}</button><button class="ntc-btn" id="ntcReplayBack">◀ Step</button><button class="ntc-btn" id="ntcReplayNext">Step ▶</button><select id="ntcReplaySpeed"><option value="0.5">0.5×</option><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option><option value="8">8×</option></select><input id="ntcReplayRange" type="range" min="0" max="${Math.max(0,total-1)}" value="${this.index}"><span>${c?esc(c.time):"—"}</span></div><div class="ntc-replay-trade"><b>Replay account</b><span>Cash ${money(this.cash)}</span><span>Pos ${this.qty}</span><span>Equity ${money(acct)}</span><input id="ntcReplayQty" type="number" min="1" step="1" value="100"><button class="ntc-btn buy" id="ntcReplayBuy">Buy</button><button class="ntc-btn sell" id="ntcReplaySell">Sell</button><button class="ntc-btn" id="ntcReplayReset">Reset</button></div><div class="ntc-replay-journal"><h4>Trade journal</h4>${this.journal.slice(0,80).map(t=>`<div><span>${esc(t.date)}</span><b>${t.action} ${t.qty}</b><span>${money(t.price)}</span><span>${t.pnl?money(t.pnl):"—"}</span></div>`).join("")||`<div class="empty">No replay trades yet.</div>`}</div><div class="ntc-backtest"><h4>Backtest — EMA crossover</h4><div class="ntc-backtest-form"><label>Fast <input id="ntcBtFast" value="10" type="number" min="2"></label><label>Slow <input id="ntcBtSlow" value="20" type="number" min="3"></label><label>Cash <input id="ntcBtCash" value="1000000" type="number" min="1000"></label><label>Fees bps <input id="ntcBtFees" value="10" type="number" min="0"></label><button class="ntc-btn primary" id="ntcRunBacktest">Run backtest</button></div><div id="ntcBacktestResult"><div class="ntc-replay-note">Uses the full historical dataset, with signals calculated only from bars available at each decision point.</div></div></div>`;this.bind()}
    bind(){this.body.querySelector("#ntcReplayClose").onclick=()=>this.close();this.body.querySelector("#ntcReplayStart").onclick=()=>{if(this.running)this.stop();else this.play();this.render()};this.body.querySelector("#ntcReplayBack").onclick=()=>this.step(-1);this.body.querySelector("#ntcReplayNext").onclick=()=>this.step(1);const range=this.body.querySelector("#ntcReplayRange");range.oninput=()=>{this.stop();this.index=Number(range.value);this.apply()};const speed=this.body.querySelector("#ntcReplaySpeed");speed.value=String(this.speed);speed.onchange=()=>{this.speed=Number(speed.value)||1;this._save()};this.body.querySelector("#ntcReplayBuy").onclick=()=>this.order("buy");this.body.querySelector("#ntcReplaySell").onclick=()=>this.order("sell");this.body.querySelector("#ntcReplayReset").onclick=()=>{this.stop();this.resetAccount();this.apply()};this.body.querySelector("#ntcRunBacktest").onclick=()=>this.runBacktest()}
  }
  global.NTC_Replay=Replay;
})(window);
